e
StructuredOutputValidationError("Failed to parse structured output for tool 'FlightAgentResponse': Failed to parse data to FlightAgentResponse: 1 validation error for FlightAgentResponse\nrecommendedFlights\n  Field required [type=missing, input_value={'response': 'Booked', 'b...stinationCity': 'Tokyo'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.13/v/missing.")
special variables:
function variables:
ai_message: AIMessage(content='{"response":"Booked","bookFlight":{"id":"FL003","airline":"United Airlines","flight_number":"UA839","departure_city":"Dallas","arrival_city":"Tokyo Narita","departure_time":"10:00","arrival_time":"14:15+1","duration":"12h15m","stops":"0","booking_class":"Economy","price":"780","currency":"USD"},"originCity":"Dallas","destinationCity":"Tokyo"}', additional_kwargs={'parsed': None, 'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 96, 'prompt_tokens': 1035, 'total_tokens': 1131, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0, 'text_tokens': None}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0, 'image_tokens': None, 'text_tokens': None}}, 'model_provider': 'openai', 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_0f73d3cd5e', 'id': 'chatcmpl-ELacfjsv10Q9EReububg7uGMFvwIR', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, name='FLIGHT_AGENT', id='lc_run--01a07da5-2a02-72d2-a9a0-021de92aad9f-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 1035, 'output_tokens': 96, 'total_tokens': 1131, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})
special variables:
function variables:
additional_kwargs: {'parsed': None, 'refusal': None}
content: '{"response":"Booked","bookFlight":{"id":"FL003","airline":"United Airlines","flight_number":"UA839","departure_city":"Dallas","arrival_city":"Tokyo Narita","departure_time":"10:00","arrival_time":"14:15+1","duration":"12h15m","stops":"0","booking_class":"Economy","price":"780","currency":"USD"},"originCity":"Dallas","destinationCity":"Tokyo"}'
content_blocks: [{'type': 'text', 'text': '{"response":"Booked","bookFlight":{"id":"FL003","airline":"United Airlines","flight_n...nCity":"Dallas","destinationCity":"Tokyo"}'}]
id: 'lc_run--01a07da5-2a02-72d2-a9a0-021de92aad9f-0'
invalid_tool_calls: []
lc_attributes: {'tool_calls': [], 'invalid_tool_calls': []}
lc_secrets: {}
model_computed_fields: {}
model_config: {'extra': 'allow'}
model_extra: {}
model_fields: {'content': FieldInfo(annotation=Union[str, list[Union[str, dict[Any, Any]]]], required=True), 'additional_kwargs': FieldInfo(annotation=dict[Any, Any], required=False, default_factory=dict), 'response_metadata': FieldInfo(annotation=dict[Any, Any], required=False, default_factory=dict), 'type': FieldInfo(annotation=Literal['ai'], required=False, default='ai'), 'name': FieldInfo(annotation=Union[str, NoneType], required=False, default=None), 'id': FieldInfo(annotation=Union[str, NoneType], required=False, default=None, metadata=[_P...eralMetadata(coerce_numbers_to_str=True)]), 'tool_calls': FieldInfo(annotation=list[ToolCall], required=False, default_factory=list), 'invalid_tool_calls': FieldInfo(annotation=list[InvalidToolCall], required=False, default_factory=list), 'usage_metadata': FieldInfo(annotation=Union[UsageMetadata, NoneType], required=False, default=None)}
model_fields_set: {'name', 'additional_kwargs', 'response_metadata', 'tool_calls', 'id', 'invalid_tool_calls', 'usage_metadata', 'content'}
name: 'FLIGHT_AGENT'
response_metadata: {'token_usage': {'completion_tokens': 96, 'prompt_tokens': 1035, 'total_tokens': 1131, 'completion_tokens_details': {...}, 'prompt_tokens_details': {...}}, 'model_provider': 'openai', 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_0f73d3cd5e', 'id': 'chatcmpl-ELacfjsv10Q9EReububg7uGMFvwIR', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}
text: '{"response":"Booked","bookFlight":{"id":"FL003","airline":"United Airlines","flight_number":"UA839","departure_city":"Dallas","arrival_city":"Tokyo Narita","departure_time":"10:00","arrival_time":"14:15+1","duration":"12h15m","stops":"0","booking_class":"Economy","price":"780","currency":"USD"},"originCity":"Dallas","destinationCity":"Tokyo"}'
tool_calls: []
type: 'ai'
usage_metadata: {'input_tokens': 1035, 'output_tokens': 96, 'total_tokens': 1131, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}
_abc_impl: <_abc._abc_data object at 0x000002CA8AB96240>
_backwards_compat_tool_calls: <bound method AIMessage._backwards_compat_tool_calls of <class 'langchain_core.messages.ai.AIMessage'>>
_calculate_keys: <bound method BaseModel._calculate_keys of AIMessage(content='{"response":"Booked","bookFlight":{"id":"FL003","airline":"United Airlines","flight_number":"UA839","departure_city":"Dallas","arrival_city":"Tokyo Narita","departure_time":"10:00","arrival_time":"14:15+1","duration":"12h15m","stops":"0","booking_class":"Economy","price":"780","currency":"USD"},"originCity":"Dallas","destinationCity":"Tokyo"}', additional_kwargs={'parsed': None, 'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 96, 'prompt_tokens': 1035, 'total_tokens': 1131, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0, 'text_tokens': None}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0, 'image_tokens': None, 'text_tokens': None}}, 'model_provider': 'openai', 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_0f73d3cd5e', 'id': 'chatcmpl-ELacfjsv10Q9EReububg7uGMFvwIR', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, name='FLIGHT_AGENT', id='lc_run--01a07da5-2a02-72d2-a9a0-021de92aad9f-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 1035, 'output_tokens': 96, 'total_tokens': 1131, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})>
_copy_and_set_values: <bound method BaseModel._copy_and_set_values of AIMessage(content='{"response":"Booked","bookFlight":{"id":"FL003","airline":"United Airlines","flight_number":"UA839","departure_city":"Dallas","arrival_city":"Tokyo Narita","departure_time":"10:00","arrival_time":"14:15+1","duration":"12h15m","stops":"0","booking_class":"Economy","price":"780","currency":"USD"},"originCity":"Dallas","destinationCity":"Tokyo"}', additional_kwargs={'parsed': None, 'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 96, 'prompt_tokens': 1035, 'total_tokens': 1131, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0, 'text_tokens': None}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0, 'image_tokens': None, 'text_tokens': None}}, 'model_provider': 'openai', 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_0f73d3cd5e', 'id': 'chatcmpl-ELacfjsv10Q9EReububg7uGMFvwIR', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, name='FLIGHT_AGENT', id='lc_run--01a07da5-2a02-72d2-a9a0-021de92aad9f-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 1035, 'output_tokens': 96, 'total_tokens': 1131, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})>
_get_value: <bound method BaseModel._get_value of <class 'langchain_core.messages.ai.AIMessage'>>
_iter: <bound method BaseModel._iter of AIMessage(content='{"response":"Booked","bookFlight":{"id":"FL003","airline":"United Airlines","flight_number":"UA839","departure_city":"Dallas","arrival_city":"Tokyo Narita","departure_time":"10:00","arrival_time":"14:15+1","duration":"12h15m","stops":"0","booking_class":"Economy","price":"780","currency":"USD"},"originCity":"Dallas","destinationCity":"Tokyo"}', additional_kwargs={'parsed': None, 'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 96, 'prompt_tokens': 1035, 'total_tokens': 1131, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0, 'text_tokens': None}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0, 'image_tokens': None, 'text_tokens': None}}, 'model_provider': 'openai', 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_0f73d3cd5e', 'id': 'chatcmpl-ELacfjsv10Q9EReububg7uGMFvwIR', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, name='FLIGHT_AGENT', id='lc_run--01a07da5-2a02-72d2-a9a0-021de92aad9f-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 1035, 'output_tokens': 96, 'total_tokens': 1131, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})>
_setattr_handler: <bound method BaseModel._setattr_handler of AIMessage(content='{"response":"Booked","bookFlight":{"id":"FL003","airline":"United Airlines","flight_number":"UA839","departure_city":"Dallas","arrival_city":"Tokyo Narita","departure_time":"10:00","arrival_time":"14:15+1","duration":"12h15m","stops":"0","booking_class":"Economy","price":"780","currency":"USD"},"originCity":"Dallas","destinationCity":"Tokyo"}', additional_kwargs={'parsed': None, 'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 96, 'prompt_tokens': 1035, 'total_tokens': 1131, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0, 'text_tokens': None}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0, 'image_tokens': None, 'text_tokens': None}}, 'model_provider': 'openai', 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_0f73d3cd5e', 'id': 'chatcmpl-ELacfjsv10Q9EReububg7uGMFvwIR', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, name='FLIGHT_AGENT', id='lc_run--01a07da5-2a02-72d2-a9a0-021de92aad9f-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 1035, 'output_tokens': 96, 'total_tokens': 1131, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})>
args: ("Failed to parse structured output for tool 'FlightAgentResponse...ttps://errors.pydantic.dev/2.13/v/missing.',)
source: ValueError("Failed to parse data to FlightAgentResponse: 1 validation error for FlightAgentResponse\nrecommendedFlights\n  Field required [type=missing, input_value={'response': 'Booked', 'b...stinationCity': 'Tokyo'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.13/v/missing")
tool_name: 'FlightAgentResponse'
